### ISSUE TITLE
Multiple fact sources

### ISSUE THREAD

**Issue by floogulinc** [mn-pollinators/pollinator-facts#71]
We may want to support multiple text sources for a given fact. The way to do this would be to change the current single fact source object to an array of fact source objects.

We would have to update the code that displays fact sources in the popup as well as any existing facts.

**Comment by floogulinc** [comment]
@mn-pollinators/pollinator-facts Do you think this is something we should add?

**Comment by floogulinc** [comment]
@kklamberty @UtkarshKr007 @reuterShawn @NicolasRobertson Do you think this is something we should add?

**Comment by UtkarshKr007** [comment]
With this implemented, and it would be easy to do so, we can have facts that are paraphrased from multiple sources or smaller facts from two sources as one fact card and cite both sources. Depends on **if** we are going to mix multiple sources together. I recall another point we were discussing before was the size of a fact, so I don't know if this is in direct conflict to that or not.
